/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class pratice_SayHelloToCpp */

#ifndef _Included_pratice_SayHelloToCpp
#define _Included_pratice_SayHelloToCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pratice_SayHelloToCpp
 * Method:    jniPrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pratice_SayHelloToCpp_jniPrint
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
